#![allow(unused_imports)]
/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
use libc;
use libc::*;
use utypes::*;
use ustring::*;
use utf8::*;
use utf16::*;
use uchar::*;
use uscript::*;
use uset::*;
use ucnv::*;
use uloc::*;
use ures::*;
use unorm2::*;
use ucal::*;
use udat::*;
use unum::*;
use utrans::*;
use ubidi::*;
use ushape::*;
use ucol::*;
use usearch::*;
use ubrk::*;
use uregex::*;
use usprep::*;
use uidna::*;
use uspoof::*;
use utmscale::*;
use umachine::*;
use parseerr::*;
use utext::*;
use uversion::*;
use uiter::*;
use uenum::*;
use urep::*;
use udisplaycontext::*;
use umisc::*;
use ufieldpositer::*;
use ucnv_err::*;

#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum UFormattableType {
    UFMT_DATE = 0,
    UFMT_DOUBLE = 1,
    UFMT_LONG = 2,
    UFMT_STRING = 3,
    UFMT_ARRAY = 4,
    UFMT_INT64 = 5,
    UFMT_OBJECT = 6,
    UFMT_COUNT = 7,
}
pub type UFormattable = *mut ::std::os::raw::c_void;
#[link(name = "icuuc", kind = "dylib")]
#[link(name = "icudata", kind = "dylib")]
extern "C" {
    pub fn ufmt_open_57(status: *mut UErrorCode) -> *mut UFormattable;
    pub fn ufmt_close_57(fmt: *mut UFormattable);
    pub fn ufmt_getType_57(fmt: *const UFormattable, status: *mut UErrorCode)
     -> UFormattableType;
    pub fn ufmt_isNumeric_57(fmt: *const UFormattable) -> UBool;
    pub fn ufmt_getDate_57(fmt: *const UFormattable, status: *mut UErrorCode)
     -> UDate;
    pub fn ufmt_getDouble_57(fmt: *mut UFormattable, status: *mut UErrorCode)
     -> f64;
    pub fn ufmt_getLong_57(fmt: *mut UFormattable, status: *mut UErrorCode)
     -> int32_t;
    pub fn ufmt_getInt64_57(fmt: *mut UFormattable, status: *mut UErrorCode)
     -> int64_t;
    pub fn ufmt_getObject_57(fmt: *const UFormattable,
                             status: *mut UErrorCode)
     -> *const ::std::os::raw::c_void;
    pub fn ufmt_getUChars_57(fmt: *mut UFormattable, len: *mut int32_t,
                             status: *mut UErrorCode) -> *const UChar;
    pub fn ufmt_getArrayLength_57(fmt: *const UFormattable,
                                  status: *mut UErrorCode) -> int32_t;
    pub fn ufmt_getArrayItemByIndex_57(fmt: *mut UFormattable, n: int32_t,
                                       status: *mut UErrorCode)
     -> *mut UFormattable;
    pub fn ufmt_getDecNumChars_57(fmt: *mut UFormattable, len: *mut int32_t,
                                  status: *mut UErrorCode)
     -> *const ::std::os::raw::c_char;
}
