#![allow(unused_imports)]
/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
use libc;
use libc::*;
use utypes::*;
use ustring::*;
use utf8::*;
use utf16::*;
use uchar::*;
use uscript::*;
use uset::*;
use ucnv::*;
use uloc::*;
use ures::*;
use unorm2::*;
use ucal::*;
use udat::*;
use unum::*;
use utrans::*;
use ubidi::*;
use ushape::*;
use ucol::*;
use usearch::*;
use ubrk::*;
use uregex::*;
use usprep::*;
use uidna::*;
use uspoof::*;
use utmscale::*;
use umachine::*;
use parseerr::*;
use utext::*;
use uiter::*;
use uenum::*;
use urep::*;
use udisplaycontext::*;
use uformattable::*;
use umisc::*;
use ufieldpositer::*;
use ucnv_err::*;

pub type UVersionInfo = [uint8_t; 4usize];
#[link(name = "icuuc", kind = "dylib")]
#[link(name = "icudata", kind = "dylib")]
extern "C" {
    pub fn u_versionFromString_57(versionArray: UVersionInfo,
                                  versionString:
                                      *const ::std::os::raw::c_char);
    pub fn u_versionFromUString_57(versionArray: UVersionInfo,
                                   versionString: *const UChar);
    pub fn u_versionToString_57(versionArray: UVersionInfo,
                                versionString: *mut ::std::os::raw::c_char);
    pub fn u_getVersion_57(versionArray: UVersionInfo);
}
